language: php

sudo: required

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - 7.3

env:
    global:
        - TEST_COMMAND="composer test"

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"
       -  php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.3
          env: USE_ASYNC=true

before_install:
    - travis_retry composer self-update
    - if [[ "$USE_ASYNC" = true ]]; then git clone https://github.com/concurrent-php/ext-async.git /tmp/async; fi
    - if [[ "$USE_ASYNC" = true ]]; then cd /tmp/async && phpize && ./configure && sudo make install; fi
    - if [[ "$USE_ASYNC" = true ]]; then echo "extension = async.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && php -m && cd $TRAVIS_BUILD_DIR; fi

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction --ignore-platform-reqs

before_script:
    - vendor/bin/http_test_server > /dev/null 2>&1 &

script:
    - cd ./tests/server/ssl && ./generate.sh && pwd && ls -la && cd ../../../
    - $TEST_COMMAND
    - ./vendor/bin/phpunit tests/SocketClientFeatureTest.php --printer Http\\Client\\Tests\\FeatureTestListener || echo ""

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
